"apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- prometheus.yaml
- grafana.yaml" > /tmp/flux-test-check/manifests/monitoring/kube-prometheus-stack/kustomization.yaml
